### ISSUE TITLE
Support media queries

### ISSUE THREAD

**Issue by necolas** [defunctzombie/npm-css#14]
Needs some tests for media queries because the output is very unexpected.

Source:

```
@media (min-width:500px) {
  @import "./foo";
}
```

Expected:

```
@media (min-width:500px) {
/* .foo {} */
.foo {}
}
```

Actual:

```
/* .foo {} */
.foo {}
```

Another example.

Source:

```
@import "./foo";

@media (min-width:500px) {
  @import "./foo";
}
```

Expected:

```
/* .foo {} */
.foo {}

@media (min-width:500px) {

}
```

Actual:

```
/* .foo {} */
.foo {}



```

How important is it to you that `@import` is used in a way that wouldn't completely break without npm-css? That would help define what the output should be for these kinds of inputs.

**Comment by Jiab77** [comment]
it's worst than that ! It doesn't handle at all any "@" inside your css...

Please fix this issue ^^
